# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d30ab6165064821d5f69233a185e375830c02218e02feca56bd11db4dd62c6ad751b30d5783fb81f5218f413cb69369b9432065ff98d0d4bbb95a1471e7f0522

test:
  secret_key_base: 6fd64c210fbc379430b80c0520f121b5b2dcab51bd181d6e4e8314ec8075d25cfac66bb0ed0542698e4a7ef7e6bebbae94915099f9fc722abf203ef7b7173579

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
